name: build
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py27-plain-cover (ubuntu)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-plain-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py27-plain-cover (windows)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-plain-cover,codecov'
            os: 'windows-latest'
          - name: 'py27-plain-cover (macos)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-plain-cover,codecov'
            os: 'macos-latest'
          - name: 'py27-plain-nocov (ubuntu)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-plain-nocov'
            os: 'ubuntu-latest'
          - name: 'py27-plain-nocov (windows)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-plain-nocov'
            os: 'windows-latest'
          - name: 'py27-plain-nocov (macos)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-plain-nocov'
            os: 'macos-latest'
          - name: 'py27-pdbpp-cover (ubuntu)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-pdbpp-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py27-pdbpp-cover (windows)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-pdbpp-cover,codecov'
            os: 'windows-latest'
          - name: 'py27-pdbpp-cover (macos)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-pdbpp-cover,codecov'
            os: 'macos-latest'
          - name: 'py27-pdbpp-nocov (ubuntu)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-pdbpp-nocov'
            os: 'ubuntu-latest'
          - name: 'py27-pdbpp-nocov (windows)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-pdbpp-nocov'
            os: 'windows-latest'
          - name: 'py27-pdbpp-nocov (macos)'
            python: '2.7'
            toxpython: 'python2.7'
            python_arch: 'x64'
            tox_env: 'py27-pdbpp-nocov'
            os: 'macos-latest'
          - name: 'py35-plain-cover (ubuntu)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-plain-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py35-plain-cover (windows)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-plain-cover,codecov'
            os: 'windows-latest'
          - name: 'py35-plain-cover (macos)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-plain-cover,codecov'
            os: 'macos-latest'
          - name: 'py35-plain-nocov (ubuntu)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-plain-nocov'
            os: 'ubuntu-latest'
          - name: 'py35-plain-nocov (windows)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-plain-nocov'
            os: 'windows-latest'
          - name: 'py35-plain-nocov (macos)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-plain-nocov'
            os: 'macos-latest'
          - name: 'py35-pdbpp-cover (ubuntu)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-pdbpp-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py35-pdbpp-cover (windows)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-pdbpp-cover,codecov'
            os: 'windows-latest'
          - name: 'py35-pdbpp-cover (macos)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-pdbpp-cover,codecov'
            os: 'macos-latest'
          - name: 'py35-pdbpp-nocov (ubuntu)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-pdbpp-nocov'
            os: 'ubuntu-latest'
          - name: 'py35-pdbpp-nocov (windows)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-pdbpp-nocov'
            os: 'windows-latest'
          - name: 'py35-pdbpp-nocov (macos)'
            python: '3.5'
            toxpython: 'python3.5'
            python_arch: 'x64'
            tox_env: 'py35-pdbpp-nocov'
            os: 'macos-latest'
          - name: 'py36-plain-cover (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-plain-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py36-plain-cover (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-plain-cover,codecov'
            os: 'windows-latest'
          - name: 'py36-plain-cover (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-plain-cover,codecov'
            os: 'macos-latest'
          - name: 'py36-plain-nocov (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-plain-nocov'
            os: 'ubuntu-latest'
          - name: 'py36-plain-nocov (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-plain-nocov'
            os: 'windows-latest'
          - name: 'py36-plain-nocov (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-plain-nocov'
            os: 'macos-latest'
          - name: 'py36-pdbpp-cover (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-pdbpp-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py36-pdbpp-cover (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-pdbpp-cover,codecov'
            os: 'windows-latest'
          - name: 'py36-pdbpp-cover (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-pdbpp-cover,codecov'
            os: 'macos-latest'
          - name: 'py36-pdbpp-nocov (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-pdbpp-nocov'
            os: 'ubuntu-latest'
          - name: 'py36-pdbpp-nocov (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-pdbpp-nocov'
            os: 'windows-latest'
          - name: 'py36-pdbpp-nocov (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-pdbpp-nocov'
            os: 'macos-latest'
          - name: 'py37-plain-cover (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-plain-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py37-plain-cover (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-plain-cover,codecov'
            os: 'windows-latest'
          - name: 'py37-plain-cover (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-plain-cover,codecov'
            os: 'macos-latest'
          - name: 'py37-plain-nocov (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-plain-nocov'
            os: 'ubuntu-latest'
          - name: 'py37-plain-nocov (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-plain-nocov'
            os: 'windows-latest'
          - name: 'py37-plain-nocov (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-plain-nocov'
            os: 'macos-latest'
          - name: 'py37-pdbpp-cover (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-pdbpp-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py37-pdbpp-cover (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-pdbpp-cover,codecov'
            os: 'windows-latest'
          - name: 'py37-pdbpp-cover (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-pdbpp-cover,codecov'
            os: 'macos-latest'
          - name: 'py37-pdbpp-nocov (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-pdbpp-nocov'
            os: 'ubuntu-latest'
          - name: 'py37-pdbpp-nocov (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-pdbpp-nocov'
            os: 'windows-latest'
          - name: 'py37-pdbpp-nocov (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-pdbpp-nocov'
            os: 'macos-latest'
          - name: 'py38-plain-cover (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-plain-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py38-plain-cover (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-plain-cover,codecov'
            os: 'windows-latest'
          - name: 'py38-plain-cover (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-plain-cover,codecov'
            os: 'macos-latest'
          - name: 'py38-plain-nocov (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-plain-nocov'
            os: 'ubuntu-latest'
          - name: 'py38-plain-nocov (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-plain-nocov'
            os: 'windows-latest'
          - name: 'py38-plain-nocov (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-plain-nocov'
            os: 'macos-latest'
          - name: 'py38-pdbpp-cover (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pdbpp-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'py38-pdbpp-cover (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pdbpp-cover,codecov'
            os: 'windows-latest'
          - name: 'py38-pdbpp-cover (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pdbpp-cover,codecov'
            os: 'macos-latest'
          - name: 'py38-pdbpp-nocov (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pdbpp-nocov'
            os: 'ubuntu-latest'
          - name: 'py38-pdbpp-nocov (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pdbpp-nocov'
            os: 'windows-latest'
          - name: 'py38-pdbpp-nocov (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-pdbpp-nocov'
            os: 'macos-latest'
          - name: 'pypy-plain-cover (ubuntu)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-plain-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy-plain-cover (windows)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-plain-cover,codecov'
            os: 'windows-latest'
          - name: 'pypy-plain-cover (macos)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-plain-cover,codecov'
            os: 'macos-latest'
          - name: 'pypy-plain-nocov (ubuntu)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-plain-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy-plain-nocov (windows)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-plain-nocov'
            os: 'windows-latest'
          - name: 'pypy-plain-nocov (macos)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-plain-nocov'
            os: 'macos-latest'
          - name: 'pypy-pdbpp-cover (ubuntu)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-pdbpp-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy-pdbpp-cover (windows)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-pdbpp-cover,codecov'
            os: 'windows-latest'
          - name: 'pypy-pdbpp-cover (macos)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-pdbpp-cover,codecov'
            os: 'macos-latest'
          - name: 'pypy-pdbpp-nocov (ubuntu)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-pdbpp-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy-pdbpp-nocov (windows)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-pdbpp-nocov'
            os: 'windows-latest'
          - name: 'pypy-pdbpp-nocov (macos)'
            python: 'pypy-.'
            toxpython: 'pypy.'
            python_arch: 'x64'
            tox_env: 'pypy-pdbpp-nocov'
            os: 'macos-latest'
          - name: 'pypy3-plain-cover (ubuntu)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-plain-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy3-plain-cover (windows)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-plain-cover,codecov'
            os: 'windows-latest'
          - name: 'pypy3-plain-cover (macos)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-plain-cover,codecov'
            os: 'macos-latest'
          - name: 'pypy3-plain-nocov (ubuntu)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-plain-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy3-plain-nocov (windows)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-plain-nocov'
            os: 'windows-latest'
          - name: 'pypy3-plain-nocov (macos)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-plain-nocov'
            os: 'macos-latest'
          - name: 'pypy3-pdbpp-cover (ubuntu)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-pdbpp-cover,codecov'
            os: 'ubuntu-latest'
          - name: 'pypy3-pdbpp-cover (windows)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-pdbpp-cover,codecov'
            os: 'windows-latest'
          - name: 'pypy3-pdbpp-cover (macos)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-pdbpp-cover,codecov'
            os: 'macos-latest'
          - name: 'pypy3-pdbpp-nocov (ubuntu)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-pdbpp-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy3-pdbpp-nocov (windows)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-pdbpp-nocov'
            os: 'windows-latest'
          - name: 'pypy3-pdbpp-nocov (macos)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-pdbpp-nocov'
            os: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: >
        tox -e ${{ matrix.tox_env }} -v
